[versions]
agp = "8.11.0"

[libraries]
#noinspection NewerVersionAvailable
gson = { module = "com.google.code.gson:gson", version = "2.7" }
xposed = { module = "de.robv.android.xposed:api", version = "82" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }